### ISSUE TITLE
is this demo source empty?

### ISSUE THREAD

**Issue by whidbey** [rrag/stockcharts-demo#2]
need to learn it.. thanks..

**Comment by rrag** [comment]
I have not had the time to make this open source. do not depend on this being oss, it is very low on my todo list.

EDIT; I mean do not depend on the demo being released as OSS soon, the react-stockcharts is and will remain oss under MIT

**Comment by whidbey** [comment]
thank you.. I just want to find a example how to add a chart dynamic... as the stockchart-examples don't have this.
